### ISSUE TITLE
Angular breaks when trying to inject deviceDetector

### ISSUE THREAD

**Issue by andre-idrive** [srfrnk/ng-device-detector#85]
I added "ng.deviceDetector" to the controller params...
`.controller('viewSupplyASNController', ['$scope', '$http', 'BBGlobals', 'dmSupplyAsn', '$location', '$stateParams', 'ng.deviceDetector', '$state', function...`

and it caused all of my binding to break. The error in the console says...

`angular.js:13236 Error: [$injector:unpr] http://errors.angularjs.org/1.5.0/$injector/unpr?p0=ng.deviceDetectorProvider%20%3C-%20ng.deviceDetector%20%3C-%20viewSupplyASNController
    at http://localhost:1024/bower_components/angular/angular.min.js:6:416
    at http://localhost:1024/bower_components/angular/angular.min.js:43:7
    at Object.d [as get] (http://localhost:1024/bower_components/angular/angular.min.js:40:270)
    at http://localhost:1024/bower_components/angular/angular.min.js:43:69
    at d (http://localhost:1024/bower_components/angular/angular.min.js:40:270)
    at e (http://localhost:1024/bower_components/angular/angular.min.js:41:1)
    at Object.instantiate (http://localhost:1024/bower_components/angular/angular.min.js:41:364)
    at http://localhost:1024/bower_components/angular/angular.min.js:87:42
    at http://localhost:1024/bower_components/angular-ui-router/release/angular-ui-router.min.js:7:23742
    at ka (http://localhost:1024/bower_components/angular/angular.min.js:79:16) <div ui-view="" class="ng-scope">`

Do you possibly know what is happening?

**Comment by srfrnk** [comment]
Sorry for the delay.
Could you create a CodePen or anyother way for me to reproduce the problem?

**Comment by andre-idrive** [comment]
Hi,
We went another route. Sorry to waste your time. Thank you for the response though!
